#!/usr/bin/env bash

#     _  _____ _____ _   _
#    / \|_   _|_   _| \ | |
#   / _ \ | |   | | |  \| |
#  / ___ \| |   | | | |\  |
# /_/   \_\_|   |_| |_| \_|
#
# This file is borrowed from awseward/dw-misc temporarily for expediency.
#
# Please refrain from modifying it in this repo, as it will eventually be
# included automatically as part of build/deploy procedure.
#

set -euo pipefail

readonly sj_access_name="${SJ_ACCESS_NAME:-dw-write}"
readonly sj_shelf_life="${SJ_SHELF_LIFE:-10 days}"

readonly sqlite_file="$1"
readonly sj_prefix="$2"

readonly now_s="$(date -u +%Y%m%d%H%M%S)"
readonly sj_filename="$(
  mktemp -u -t "${now_s}-XXXXXXXX-$(basename "${sqlite_file}")" | xargs basename
)"

echo "${sj_access_name}" \
  | xargs -t  uplink cp "${sqlite_file}" "${sj_prefix}/${sj_filename}" \
                --progress=false \
                --expires="$(date -d "${sj_shelf_life}" -u +%FT%TZ)" \
                --access \
  | sed -E 's/^Created //' \
  && (
    echo "${sqlite_file}" | xargs -t >&2 rm -fv -- # Remove file on success
  )
