#!/usr/bin/env bash

set -euo pipefail

git remote show heroku \
  && >&2 echo -e "\nERROR: Found an existing git remote named 'heroku'. Aborting." \
  && exit 1

heroku create --buildpack heroku/nodejs

heroku buildpacks:add https://github.com/awseward/heroku-buildpack-nim
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-apt
heroku buildpacks:add https://github.com/niteoweb/heroku-buildpack-shell

heroku addons:create heroku-postgresql:hobby-dev

heroku config:set IS_HEROKU=true
heroku config:set NIM_REV=3fb5157ab1b666a5a5c34efde0f357a82d433d04 # → v1.4.2
heroku config:set NIMBLE_FLAGS='--define:release --define:ssl --stacktrace:on --linetrace:on'
heroku config:set MQTT_SERVER=mqtt://192.168.86.20:1883
heroku config:set MQTT_TOPIC=call-status/people

git push heroku master
