#!/usr/bin/env bash

set -euo pipefail

git remote show heroku \
  && >&2 echo -e "\nERROR: Found an existing git remote named 'heroku'. Aborting." \
  && exit 1

heroku create

heroku buildpacks:add https://github.com/awseward/heroku-buildpack-nim
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-apt

heroku addons:create heroku-postgresql:hobby-dev

heroku config:set DW_INGEST_URL=__FIXME__
heroku config:set IS_HEROKU=true
heroku config:set LOCAL_HISTORY_RETENTION='3 days'
heroku config:set MQTT_SERVER=mqtt://192.168.86.20:1883
heroku config:set MQTT_TOPIC=call-status/people
heroku config:set MQTT_TOPIC_CONTROL=call-status/control
heroku config:set MQTT_TOPIC_HEARTBEAT=call-status/heartbeat
heroku config:set MQTT_TOPIC_PEOPLE=call-status/people
heroku config:set NIM_REV=727c6378d2464090564dbcd9bc8b9ac648467e38 # → v1.6.0
heroku config:set NIMBLE_FLAGS='--define:release --define:ssl --define:useStdLib --stacktrace:on --linetrace:on --verbose'
heroku config:set SJ_ACCESS=__FIXME__

git push heroku master
