name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y nimassets
    - run: nimble assets
    - run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble build -y

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y
    - run: nimble docs
