name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y nimassets
    - run: nimble assets
    - run: git diff --exit-code

  build-call_status_checker:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble build dump

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y
    - run: nimble build dump --verbose

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y
    - run: nimble docs
