name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.0.2
    - run: nimble install nimassets

    - name: Check assets file
      run: |
        nimble install -y nimassets
        nimassets --dir=public --output=src/views/assetsFile.nim
        git diff --exit-code


    - run: nimble build -Y
