name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  check_assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble install -y nimassets
    - run: nimassets --dir=public --output=src/views/assetsFile.nim
    - run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2

    - run: nimble build -y
