jobs:
  build-call_status_checker:
    runs-on:
      - macos-latest
    steps:
      - uses: "actions/checkout@v2"
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-nimble-${{ hashFiles('**/*.nimble') }}"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.3.4"
        with:
          nim-version: '1.6.6'
      - run: script/gh-actions-ci.sh build_call_status_checker
  build-web:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-nimble-${{ hashFiles('**/*.nimble') }}"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.3.4"
        with:
          nim-version: '1.6.6'
      - run: script/gh-actions-ci.sh build_web
  check-assets:
    runs-on:
      - macos-latest
    steps:
      - uses: "actions/checkout@v2"
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-nimble-${{ hashFiles('**/*.nimble') }}"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.3.4"
        with:
          nim-version: '1.6.6'
      - run: script/gh-actions-ci.sh check_assets
  check-shell:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "awseward/gh-actions-shell@0.1.5"
  generate-docs:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-nimble-${{ hashFiles('**/*.nimble') }}"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.3.4"
        with:
          nim-version: '1.6.6'
      - run: script/gh-actions-ci.sh generate_docs
name: CI
on:
  pull_request:
    branches:
      - main
