name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  assets:
    # FIXME: Solve the entry ordering discrepancy between different runners and
    # then turn this job back on
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.1.4

    - run: nimble install -y nimassets
    - run: nimble assets
    - run: git diff --exit-code --color

  build-call_status_checker:
    # FIXME: Solve the flaky cache issue and then turn this job back on
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version: 1.2.0

    # (for some reason even w/ a valid binary)
    - run: echo nimble build -y call_status_checker
    - run: nimble build -y

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version: 1.2.0

    - run: nimble build --accept

  docs:
    # FIXME: Figure out what's actually wrong-- I have a feeling it's just a
    # nimble version thing or something; in the meantime, wasn't really doing
    # anything with these anyway so we're fine to just skip for now.
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.1.4

    - run: nimble install -y
    - run: nimble docs
