# This is a dumpster fire, but will be replaced with a sane version before long…

name: Meta
on:
  - push
jobs:
  check-workflow-templates:
    runs-on:
      - ubuntu-latest
    continue-on-error: true
    steps:
      - uses: "actions/checkout@v2"

      - name: Install Dhall
        uses: awseward/dhall-setup@main

      - name: Check Templates
        run: script/gi-actions-meta.sh check_workflow_templates
