jobs:
  release-call_status_checker:
    runs-on:
      - macos-latest
    steps:
      - uses: "actions/checkout@v2"
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-nimble-${{ hashFiles('**/*.nimble') }}"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.3.4"
        with:
          nim-version: '1.6.6'
      - id: plan
        name: Plan release
        run: script/gh-actions-release.sh plan
      - id: tarball
        name: Create tarball
        run: script/gh-actions-release.sh create_tarball
      - id: checksum
        name: Record checksum
        run: script/gh-actions-release.sh record_checksum
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: create-release
        uses: "actions/create-release@v1"
        with:
          body: "Checksum: `${{ steps.checksum.outputs.tarball_checksum }}`"
          draft: false
          prerelease: false
          release_name: "${{ steps.plan.outputs.git_tag }}"
          tag_name: "${{ steps.plan.outputs.git_tag }}"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: upload-tarball
        uses: "actions/upload-release-asset@v1"
        with:
          asset_content_type: application/gzip
          asset_name: "${{ steps.tarball.outputs.tarball_filename }}"
          asset_path: "${{ steps.tarball.outputs.tarball_filepath }}"
          upload_url: "${{ steps.create-release.outputs.upload_url }}"
      - env:
          COMMITTER_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
        uses: "mislav/bump-homebrew-formula-action@v1"
        with:
          base-branch: main
          commit-message: |
            {{formulaName}} {{version}}

            Sourced from ${{ steps.create-release.outputs.html_url }}.
          download-url: "${{ steps.upload-tarball.outputs.browser_download_url }}"
          formula-name: call_status_checker
          homebrew-tap: awseward/homebrew-tap
name: Release
on:
  push:
    tags:
      - "*"
